config/routes.rb
# frozen_string_literal: true

class Blacklist
  def matches?(request)
    !BannedIp.exists? ip: request.remote_ip
  end
end

Catarse::Application.routes.draw do
  constraints Blacklist.new do
    mount RedactorRails::Engine => '/redactor_rails'
    mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
    devise_for(
      :users,
      {
        path: '',
        path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
        controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords, sessions: :sessions }
      }
    )

    devise_scope :user do
      post '/sign_up', { to: 'devise/registrations#create', as: :sign_up }
      get '/not-my-account', to: 'sessions#destroy_and_redirect', as: :not_my_account
    end

    # User permalink profile
    constraints SubdomainConstraint do
      get '/', to: 'users#show'
    end

    get '/amigos' => redirect('http://crowdfunding.catarse.me/amigos')
    get '/criadores' => redirect('http://crowdfunding.catarse.me/criadores')
    get '/paratodos' => redirect('http://crowdfunding.catarse.me/paratodos')

    get '/support_forum' => 'zendesk_sessions#create', as: :zendesk_session_create
    get '/posts' => 'application#get_blog_posts'
    get '/project_edit' => 'application#redirect_to_last_edit'
    get '/billing_edit' => 'application#redirect_to_user_billing'
    get '/user_contributions' => 'application#redirect_to_user_contributions'
    post '/subscribe_newsletter' => 'mail_marketing_users#subscribe'
    get '/unsubscribe_list' => 'mail_marketing_users#unsubscribe'

    get '/thank_you' => 'static#thank_you'
    get '/follow-fb-friends' => 'users#follow_fb_friends', as: :follow_fb_friends
    get '/connect-facebook' => 'application#connect_facebook', as: :connect_fb

    get '/notifications/:notification_type/:notification_id' => 'notifications#show'

    filter :locale, exclude: /\/auth\//

    mount CatarsePagarme::Engine => '/', as: :catarse_pagarme
    # mount CatarseWepay::Engine => "/", as: :catarse_wepay
    mount Dbhero::Engine => '/dbhero', as: :dbhero

    resources :home_banners, path: '/home_banners', controller: 'home/banners'

    resources :categories, only: [] do
      member do
        get :subscribe, to: 'categories/subscriptions#create'
        get :unsubscribe, to: 'categories/subscriptions#destroy'
      end
    end
    resources :auto_complete_projects, only: [:index]
    resources :auto_complete_cities, only: [:index]
    resources :rewards, only: [] do
      resources :surveys, only: [:create, :update], controller: 'surveys'
    end
    resources :projects, path: '/', only: [:index]
    resources :flexible_projects, path: '/', controller: 'projects', only: [:index]
    # @TODO update links, we don't need this anymore
    resources :flexible_projects, controller: 'projects', except: [:index] do
      member do
        get :publish
        get 'publish-by-steps'
        get :push_to_online
        get :validate_publish
        get :finish
      end
    end
    resources :contributions, only: [] do
      resources :surveys, only: [:show], controller: 'surveys' do
        member do
          put :answer
        end
      end
    end
    resources :projects, only: %i[create update edit new show] do
      resources :project_report_exports, controller: 'projects/project_report_exports'
      get 'subscriptions/:any', to: 'projects#show', on: :member
      post 'subscriptions/:any', to: 'projects#show', on: :member
      resources :accounts, only: %i[create update]
      resources :posts, controller: 'projects/posts', only: %i[destroy show create]
      resources :goals
      resources :rewards do
        member do
          get :toggle_survey_finish
          post :upload_image
          delete :delete_image
        end
        resources :surveys, only: [:new], controller: 'surveys'
        post :sort, on: :member
      end
      get 'debit_note/:fiscal_date', to: 'projects/project_fiscal_data#debit_note'
      get 'inform/:fiscal_year', to: 'projects/project_fiscal_data#inform'
#      resources :debit_note,  { only: [:show], controller: 'projects/project_fiscal_data', action: 'debit_note' } do
#        get '/:fiscal_date', to: 'projects/project_fiscal_data#debit_note'
#      end
#      resources :inform,  { only: [:show], controller: 'projects/project_fiscal_data', action: 'inform' }
      resources :contributions, { except: [:index], controller: 'projects/contributions' } do
        collection do
          get :fallback_create, to: 'projects/contributions#create'
          put :update_status
        end
        member do
          get 'toggle_anonymous'
          get 'toggle_delivery'
          get :second_slip
          get :receipt
        end
        put :credits_checkout, on: :member
      end

      resources :integrations, { only: [:index, :create, :update], controller: 'projects/integrations' }

      collection do
        get :fallback_create, to: 'projects#create'
      end
      get 'video', on: :collection
      member do
        post :upload_image
        get 'insights'
        get 'posts'
        get 'surveys'
        get 'fiscal'
        get 'contributions_report'
        get 'subscriptions_report'
        get 'subscriptions_report_download'
        get 'subscriptions_report_for_project_owners'
        get 'subscriptions_monthly_report_for_project_owners'
        get 'download_reports'
        put 'pay'
        get 'embed'
        get 'video_embed'
        get 'embed_panel'
        get 'send_to_analysis'
        get 'publish'
        get 'publish-by-steps'
        get 'validate_publish'
        get 'push_to_online'
      end
    end
    resources :users do
      resources :credit_cards, controller: 'users/credit_cards', only: [:destroy]
      member do
        # get :balance
        post :upload_image
        get :credit_cards
        get :unsubscribe_notifications
        get :credits
        get :settings
        get :billing
        get :reactivate
        post :new_password
        post :ban
      end

      resources :unsubscribes, only: [:create]
      member do
        get 'projects'
        put 'unsubscribe_update'
        put 'update_email'
        put 'update_password'
      end
    end

    get '/terms-of-use' => redirect('https://crowdfunding.catarse.me/legal/termos-de-uso')
    get '/privacy-policy' => redirect('https://crowdfunding.catarse.me/legal/politica-de-privacidade')
    get '/start' => redirect('https://crowdfunding.catarse.me/comece')
    get '/start-sub' => redirect('https://crowdfunding.catarse.me/comece')
    get '/solidaria' => redirect('https://crowdfunding.catarse.me/solidaria')
    get '/jobs' => 'high_voltage/pages#show', id: 'jobs'
    get '/hello' => redirect('/start')
    get '/press' => redirect('https://crowdfunding.catarse.me/imprensa')
    get '/assets' => redirect('https://crowdfunding.catarse.me/assets')
    get '/guides' => redirect('http://fazum.catarse.me/guia-financiamento-coletivo')
    get '/new-admin' => 'high_voltage/pages#show', id: 'new_admin'
    get '/explore' => 'high_voltage/pages#show', id: 'explore'
    get '/team' => redirect('https://crowdfunding.catarse.me/nosso-time')
    get '/about' => redirect('https://crowdfunding.catarse.me/quem-somos')
    get '/flex' => redirect('http://crowdfunding.catarse.me')
    get '/projects_dashboard' => 'high_voltage/pages#show', id: 'projects_dashboard'

    # Root path should be after channel constraints
    root to: 'projects#index'

    namespace :reports do
      resources :contribution_reports_for_project_owners, only: [:index]
    end

    # Feedback form
    resources :feedbacks, only: [:create]

    namespace :admin do
      resources :balance_transfers do
        collection do
          post 'batch_approve'
          post 'batch_manual'
          post 'batch_reject'
          #post 'process_transfers'
        end
      end

      resources :projects, :flexible_projects, controller: 'projects', only: %i[index update destroy] do
        member do
          put :revert_or_finish
          put 'approve'
          put 'push_to_online'
          put 'reject'
          put 'push_to_draft'
          put 'push_to_trash'
        end
      end

      resources :financials, only: [:index]

      resources :subscription_payments do
        collection do
          post :batch_chargeback
        end
      end

      resources :contributions, only: [] do
        member do
          put 'gateway_refund'
        end
        collection do
          post 'batch_chargeback'
        end
      end

      namespace :reports do
        resources :contribution_reports, only: [:index]
      end
    end

    resource :api_token, only: [:show] do
      collection do
        get :common
        get :common_proxy
      end
    end

    get '/:permalink' => 'projects#show', as: :project_by_slug
  end
end

app/models/concerns/shared/bank_account_helper.rb
# frozen_string_literal: true

module Shared::BankAccountHelper
  extend ActiveSupport::Concern

  included do
    validates :account, format: { with: /\A\d+\z/ }

    # if input_bank_number as present, we
    # should validate if the number matchs with any
    # bank.code on database
    def input_bank_number_validation
      if input_bank_number.present? && !bank_from_input_number.present?
        errors.add(:input_bank_number, :invalid)
      end
    end

    def bank_code
      bank.code
    end

    # set bank attribute with founded bank via
    # input_bank_number virtual attribute
    def load_bank_from_input_bank_number
      self.bank = bank_from_input_number if bank_from_input_number.present?
    end

    # Returns a bank object that bank number
    # matches with Bank.code
    def bank_from_input_number
      Bank.find_by_code input_bank_number
    end
  end
end

app/models/concerns/shared/chart_handler.rb
# frozen_string_literal: true

module Shared::ChartHandler
  extend ActiveSupport::Concern

  included do
    def self.chart
      series = [
        { name: I18n.t('admin.statistics.charts.current_period'), data: {} },
        { name: I18n.t('admin.statistics.charts.last_year'), data: {} }
      ]
      all.each do |data|
        series[0][:data][data.label] = data.current_year
        series[1][:data][data.label] = data.last_year
      end
      series
    end
  end
end

app/models/concerns/shared/common_wrapper.rb
# frozen_string_literal: true

module Shared::CommonWrapper
  extend ActiveSupport::Concern

  included do
    def common_wrapper
      return unless CatarseSettings[:common_api_key].present? || CatarseSettings[:common_proxy_api_key].present?
      @common_wrapper ||= ::CommonWrapper.new
    end
  end
end

app/models/concerns/shared/materialized_view.rb
# frozen_string_literal: true

module Shared
  module MaterializedView
    extend ActiveSupport::Concern

    included do
      def self.refresh_view
        connection.execute('SET statement_timeout TO 0;')
        connection.execute("REFRESH MATERIALIZED VIEW CONCURRENTLY #{table_name}")
      end
    end
  end
end

app/models/concerns/shared/queued.rb
# frozen_string_literal: true

module Shared::Queued
  extend ActiveSupport::Concern

  included do
    def remove_scheduled_job(worker_class_name, first_arg_c = id)
      on_scheduled_jobs(worker_class_name, first_arg_c) do |job|
        job.delete
      end
    end

    def exists_on_scheduled_jobs(class_name, args)
      scheduled_queue.any? { |j| job_match?(j, class_name, args) }
    end

    private

    def on_scheduled_jobs(class_name, first_arg_c)
      scheduled_queue.each do |job|
        yield job if job_match?(job, class_name, first_arg_c)
      end
    end

    def job_match?(job, class_name, args)
      job['class'] == class_name && (args.is_a?(Array) ? job_args == args : job_args[0] == args)
    end

    def scheduled_queue
      Sidekiq::ScheduledSet.new
    end
  end
end

app/models/concerns/shared/state_machine_helpers.rb
# frozen_string_literal: true

require 'state_machines'
module Shared
  module StateMachineHelpers
    extend ActiveSupport::Concern

    included do
      def self.state_names
        state_machine.states.map(&:name)
      end
    end
  end
end

app/models/concerns/shared/video_handler.rb
# frozen_string_literal: true

module Shared::VideoHandler
  extend ActiveSupport::Concern

  included do
    validates_format_of :video_url, with: /(https?\:\/\/|)(youtu(\.be|be\.com)|vimeo).*+/, message: I18n.t('project.video_regex_validation'), allow_blank: true

    def video
      if video_url.present?
        @video ||= begin
                     VideoInfo.get(video_url)
                   rescue
                     nil
                   end
      end
    end

    def video_valid?
      video_url.present? && video
    end

    def display_video_embed_url
      if video_embed_url
        "#{video_embed_url}?title=0&byline=0&portrait=0&autoplay=0"
      end
    end
  end
end

app/views/catarse_bootstrap/shared/_footer.html.slim
footer.footer-simple
  .w-container
    .footer-signature-text.fontsize-smallest #{CatarseSettings[:company_name]} #{Time.current.strftime("%Y")}
    ul.w-list-unstyled.footer-simple-links.fontsize-smallest
      li.footer-simple-links-list
        a.link-footer href="#{CatarseSettings[:contact_url]}"  #{t('layouts.footer.links.contact')}
      li.footer-simple-links-list
        a.link-footer href="#{press_url}"  #{t('layouts.footer.links.press')}
      li.footer-simple-links-list
        a.w-hidden-small.link-footer href="#{explore_path}"  #{t('layouts.footer.links.discover')}
      li.footer-simple-links-list
        a.w-hidden-small.link-footer href="#{guides_url}"  #{t('layouts.footer.links.guides')}
      li.footer-simple-links-list
        a.link-footer href="#{CatarseSettings[:faq_url]}"  #{t('layouts.footer.links.faq')}
      li.footer-simple-links-list
        a.link-footer href="#{terms_of_use_path}"  #{t('layouts.footer.links.terms')}
      li.footer-simple-links-list
        a.link-footer href="#{privacy_policy_path}"  #{t('layouts.footer.links.privacy')}
  .w-container
    #google_translate_element

app/views/catarse_bootstrap/shared/_footer_about.html.slim
.footer-full-signature-text.fontsize-small #{t('layouts.footer.titles.about')}
a.zendesk_widget.link-footer href="#{CatarseSettings[:zendesk_url]}/account/dropboxes/#{CatarseSettings[:zendesk_dropbox_id]}"  #{t('layouts.footer.links.contact')}
a.link-footer href="http://ano.catarse.me/2016?ref=ctrse_footer" 
  | 2016 no Catarse&nbsp;
  span.badge.badge-success Novidade‍
a.link-footer href="http://crowdfunding.catarse.me/paratodos?ref=ctrse_footer" 
  | Como funciona&nbsp;
a.link-footer href="#{press_url}"  #{t('layouts.footer.links.press')}
a.link-footer href="#{CatarseSettings[:faq_url]}"  #{t('layouts.footer.links.help_support')}
a.link-footer href="#{guides_url}"  #{t('layouts.footer.links.guides')}
a.link-footer href="http://pesquisa.catarse.me/"  #{t('layouts.footer.links.crowdfunding_stats')}
a.link-footer href="#{terms_of_use_path}"  #{t('layouts.footer.links.terms')}
a.link-footer href="#{privacy_policy_path}"  #{t('layouts.footer.links.privacy')}

app/views/catarse_bootstrap/shared/_footer_big.html.slim
footer.main-footer.main-footer-neg
  section.w-container
    .w-row
      .w-col.w-col-9
        .w-row
          .w-col.w-col-4.w-col-small-4.w-col-tiny-4.w-hidden-tiny
            = render 'shared/footer_welcome'
          .w-col.w-col-4.w-col-small-4.w-col-tiny-4.footer-full-firstcolumn
            = render 'shared/footer_about'
          .w-col.w-col-4.w-col-small-4.w-col-tiny-4.footer-full-lastcolumn
            = render 'shared/footer_navigate'
      .w-col.w-col-3.column-social-media-footer
        .footer-full-signature-text.fontsize-small Assine nossa news
        .w-form
          = render 'shared/newsletter'
        .footer-full-signature-text.fontsize-small Redes sociais
        .w-widget.w-widget-facebook.u-marginbottom-20
          = render_facebook_like colorscheme: "dark"
        .w-widget.w-widget-twitter
          = link_to "Follow @#{CatarseSettings[:twitter_username]}", "http://twitter.com/#{CatarseSettings[:twitter_username]}", :class => 'twitter-follow-button', :"data-button"=>"blue", :"data-text-color" => "#ffffff", :"data-link-color"=>"#fffffff", :"data-width" => "224px"
        .u-margintop-30
          .footer-full-signature-text.fontsize-small Change language
          #google_translate_element
  .w-container
    .footer-full-copyleft 
      = image_tag "logo-footer.png", class: "u-marginbottom-20"
      .lineheight-loose: a.link-footer-inline[href="#{CatarseSettings[:github_url]}"] Feito com amor | #{Date.today.year} | Open source

app/views/catarse_bootstrap/shared/_footer_navigate.html.slim
.footer-full-signature-text.fontsize-small #{t('layouts.footer.titles.sitemap')}
a.w-hidden-small.w-hidden-tiny.link-footer href="#{start_path(ref:'ctrse_footer')}"  #{t('layouts.footer.links.submit')}
a.link-footer href="#{explore_path(ref:'ctrse_footer')}"  #{t('layouts.footer.links.discover')}
a.w-hidden-main.w-hidden-medium.w-hidden-small.link-footer href="#{CatarseSettings[:blog_url]}"  #{t('layouts.footer.links.blog')}
a.w-hidden-main.w-hidden-medium.w-hidden-small.link-footer href="#{CatarseSettings[:zendesk_url]}/account/dropboxes/#{CatarseSettings[:zendesk_dropbox_id]}"  #{t('layouts.footer.links.contact')}
- if current_user.try(:adress_state)
  a.w-hidden-tiny.link-footer href="#{explore_path(anchor: ('near_of/' + current_user.address_state),ref:'ctrse_footer')}" #{t('layouts.footer.links.near')}
a.w-hidden-tiny.link-footer href="#{explore_path(:filter => "score",ref:'ctrse_footer')}"  #{t('layouts.footer.links.score')}
a.w-hidden-tiny.link-footer href="#{explore_path(:filter => "online",ref:'ctrse_footer')}"  #{t('layouts.footer.links.online')}
a.w-hidden-tiny.link-footer href="#{explore_path(:filter => "finished",ref:'ctrse_footer')}"  #{t('layouts.footer.links.finished')}

app/views/catarse_bootstrap/shared/_footer_welcome.html.slim
.footer-full-signature-text.fontsize-small #{t('layouts.footer.titles.contact')}
a.link-footer href="http://ano.catarse.me/2016?ref=ctrse_footer" 
  | 2016 no Catarse&nbsp;
  span.badge.badge-success Novidade‍
a.link-footer href="http://crowdfunding.catarse.me/paratodos?ref=ctrse_footer" 
  | Como funciona&nbsp;
a.link-footer href="#{team_url}"  #{t('layouts.footer.links.team')}
a.link-footer href="#{CatarseSettings[:facebook_url]}"  #{t('layouts.footer.links.facebook')}
a.link-footer href="#{CatarseSettings[:twitter_url]}"  #{t('layouts.footer.links.twitter')}
a.link-footer href="#{CatarseSettings[:instagram_url]}"  #{t('layouts.footer.links.instagram')}
a.link-footer href="#{CatarseSettings[:github_url]}"  #{t('layouts.footer.links.github')}
a.link-footer href="#{CatarseSettings[:blog_url]}?ref=ctrse_footer"  #{t('layouts.footer.links.blog')}
a.link-footer href="#{jobs_url}"  #{t('layouts.footer.links.jobs')}

app/views/catarse_bootstrap/shared/_header.html.slim
/ = render 'layouts/global_alert'
header class="main-header #{((defined?(overlayer) && overlayer) ? 'overlayer' : '')}"
  .w-row
    .w-clearfix.w-col.w-col-8.w-col-small-8.w-col-tiny-8
      = link_to (image_tag "catarse_bootstrap/logo_big.png"), root_url(subdomain: 'www'), class: 'header-logo w-nav-brand', :title => CatarseSettings[:company_name]
      = yield :header_controls
    .text-align-right.w-col.w-col-4.w-col-small-4.w-col-tiny-4
      - if current_user
        .w-dropdown.user-profile
          = link_to 'javascript:toggleMenu()', id: 'user-menu', class: 'w-dropdown-toggle dropdown-toggle' do
            .user-name-menu= current_user.display_name.split(' ').first if current_user.name
            = image_tag(current_user.display_image, :size => "40x40", class: 'user-avatar')
          = render 'shared/user_menu'
      - else
        = link_to t('layouts.header.signin'), new_user_session_path, class: 'w-nav-link header-link w-nav-link btn-edit u-right',id:'header_login_btn'
  = yield :headermobile_controls

app/views/catarse_bootstrap/shared/_header_big.html.slim
- content_for :header_controls do

  = link_to t('layouts.header.submit'), start_path(ref:'ctrse_header'), class: 'w-hidden-small w-hidden-tiny header-link w-nav-link'

  = link_to t('layouts.header.discover'), explore_path(ref:'ctrse_header'), class: 'w-hidden-small w-hidden-tiny header-link w-nav-link'

  #discover-form-wrapper.w-form.w-hidden-small.w-hidden-tiny.header-search
    = form_tag explore_path, method: 'GET', class: 'discover-form', id: 'search-form' do
      = hidden_field_tag :ref, 'ctrse_header'
      = text_field_tag :pg_search, nil, autocomplete: "off", value: params[:pg_search], class: "w-input text-field prefix search-input", placeholder: t('layouts.header.search')

    .search-pre-result.w-hidden data-searchpath=auto_complete_projects_path
      .result
        .u-text-center= image_tag "catarse_bootstrap/loader.gif"
      a.btn.btn-small.btn-terciary.see-more-projects href="javascript:void(0);"  ver todos

  = link_to '#', id: 'pg_search_submit', class: "w-inline-block w-hidden-small w-hidden-tiny btn btn-dark btn-attached postfix" do
    = image_tag "catarse_bootstrap/lupa.png", class: "header-lupa"

- content_for :headermobile_controls do
  .w-hidden-main.w-hidden-medium.header-controls-mobile
    = link_to t('layouts.header.submit'), start_path, class: 'header-link w-nav-link'
    = link_to t('layouts.header.discover'), explore_path, class: 'header-link w-nav-link'
    

= render 'shared/header', overlayer: (defined?(overlayer) && overlayer ? true : false)

app/views/catarse_bootstrap/shared/_newsletter.html.slim
= form_tag CatarseSettings['mailchimp_url'], id: 'mailee-form', method: 'post' do
  .w-form.footer-newsletter
    = email_field_tag 'EMAIL', nil, placeholder: t('projects.index.sidebar.placeholders.email'), label: 'email', class: 'w-input text-field prefix'
  = link_to '#', class: 'w-inline-block btn btn-edit postfix btn-attached' do
    = image_tag 'catarse_bootstrap/icon-newsletter.png', class: 'footer-news-icon'

app/views/catarse_bootstrap/shared/_user_menu.html.slim
- cache "user_menu_#{current_user.id}", expires_in: 2.minutes.from_now do
  nav#user-menu-dropdown.w-dropdown-list.dropdown-list.user-menu
    .w-row
      .w-col.w-col-12
        .fontweight-semibold.fontsize-smaller.u-marginbottom-10 = t('shared.menus.user.contributions_history')
        ul.w-list-unstyled.u-marginbottom-20
          li.lineheight-looser
            = link_to t('shared.menus.user.contributions_history_nav'), edit_user_path(current_user, anchor: :contributions), class: 'alt-link fontsize-smaller'
          li.lineheight-looser
            = link_to  t('shared.menus.user.projects_created'), edit_user_path(current_user, anchor: :projects), class: 'alt-link fontsize-smaller'
          /li.lineheight-looser
            = link_to  t('shared.menus.user.activity'), edit_user_path(current_user, anchor: :feeds), class: 'alt-link fontsize-smaller'
        .fontweight-semibold.fontsize-smaller.u-marginbottom-10 Configurações
        ul.w-list-unstyled.u-marginbottom-20
          li.lineheight-looser
            = link_to t('shared.menus.user.find_friends'), connect_fb_path, class: 'alt-link fontsize-smaller'
            | &nbsp;
            span.badge.badge-success
              | Novidade
          li.lineheight-looser
            = link_to t('shared.menus.user.about'), edit_user_path(current_user, anchor: :about_me), class: 'alt-link fontsize-smaller'
          li.lineheight-looser
            = link_to t('shared.menus.user.notifications'), edit_user_path(current_user, anchor: :notifications), class: 'alt-link fontsize-smaller'
          li.lineheight-looser
            = link_to t('shared.menus.user.access_address'), edit_user_path(current_user, anchor: :settings), class: 'alt-link fontsize-smaller'
        .divider.u-marginbottom-20
        - if current_user.admin?
          .fontweight-semibold.fontsize-smaller.u-marginbottom-10 Admin
          ul.w-list-unstyled.u-marginbottom-20
            li.lineheight-looser
              = link_to t('admin.users.index.menu'), new_admin_path(anchor: '/users'), class: 'alt-link fontsize-smaller'
            li.lineheight-looser
              = link_to t('admin.contributions.index.menu'), new_admin_path, class: 'alt-link fontsize-smaller'
            li.lineheight-looser
              = link_to t('admin.financials.index.menu'), admin_financials_path, class: 'alt-link fontsize-smaller'
            li.lineheight-looser
              = link_to t('admin.projects.index.menu'), admin_projects_path, class: 'alt-link fontsize-smaller'
            li.lineheight-looser
              = link_to 'Dataclips', dbhero_path, class: 'alt-link fontsize-smaller'
        .fontsize-mini= t('shared.menus.user.your_email')
        .fontsize-smallest.u-marginbottom-20
          span.fontweight-semibold= current_user.email
          = link_to t('shared.menus.user.update_email'), edit_user_path(current_user, anchor: :settings), class: 'alt-link'
        .divider.u-marginbottom-20
        = link_to t('layouts.user.logout'), destroy_user_session_path, class: 'alt-link'
        
  